loki:
  image:
    repository: grafana/loki
    tag: 2.9.3 
    pullPolicy: IfNotPresent
  enabled: true
  auth_enabled: false
  isDefault: false
  persistence:
    enabled: true
    storageClassName: longhorn # Uses RAID-backed storage
    size: 10Gi
    accessModes:
      - ReadWriteOnce

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

promtail:
  enabled: true
  # Promtail needs to run on every node to catch all logs
  config:
    lokiAddress: http://logging-stack-loki.logging.svc.cluster.local:3100/loki/api/v1/push
    clients:
      - url: http://logging-stack-loki.logging.svc.cluster.local:3100/loki/api/v1/push

# Disable things already have or don't need
grafana:
  enabled: false
prometheus:
  enabled: false
fluent-bit:
  enabled: false
