apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      # Must use the public URL for the remote GKE cluster
      server: "https://vault.sikiru.co.uk"
      path: "secret"
      version: "v2"
      
      auth:
        kubernetes:
          # STRICT SECURITY: Targets the isolated GKE auth backend
          mountPath: "kubernetes-gke"
          role: "external-secrets-role"
          
          # THE MISSING BINDING: Tells GKE ESO which token to present to Vault
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
