apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.sikiru.co.uk"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes-gke"
          role: "external-secrets-role"
