apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/JimohAdebayo-DevOps/sre-self-healing-k8s.git'
    path: k8s/cloudflare
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: n8n
  syncPolicy:
    automated:
      prune: false 
      selfHeal: true
