apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-vault-bridge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/JimohAdebayo-DevOps/sre-self-healing-k8s.git'
    path: k8s/gke-vault
    targetRevision: main
  destination:
    # Strictly target the remote GKE cluster context alias
    name: 'gke_project-e29bb3f8-b6d8-434e-811_europe-north1-a_gridops-gke-cluster'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
