apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.5
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 
      - RespectIgnoreDifferences=true # <--- CRITICAL FIX: Forces SSA to ignore the caBundle
  ignoreDifferences:
    # 1. Ignore the dynamic certificates injected into the CRDs (The true culprit!)
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - '.spec.conversion.webhook.clientConfig.caBundle'
        
    # 2. Ignore the standard Validation webhooks
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
        
    # 3. Ignore the standard Mutation webhooks
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
