apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gridops-mosquitto
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/JimohAdebayo-DevOps/sre-self-healing-k8s.git'
    path: k8s/mosquitto
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gridops-edge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
