apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-db
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.2.0      # Match your current version!
    helm:
      valueFiles:
        - postgres-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    # IMPORTANT: We leave automation OFF for the very first sync
    # to ensure it doesn't try to "re-install" over your live data.
    syncOptions:
      - CreateNamespace=true
