apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gridops-ingress
  namespace: n8n
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: portal.sikiru.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gridops-service
                port:
                  number: 80
  tls:
    - hosts:
        - portal.sikiru.co.uk
      secretName: gridops-tls

