apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-broker
  namespace: gridops-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1883
        fsGroup: 1883
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.18
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto-config
