apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: gridops-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:3.0-edge  # Utilizing the v3 IOx Engine
          ports:
            - containerPort: 8086
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: gridops-admin
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials-secret
                  key: admin-password
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: GridOps
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: electrical_telemetry
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb2
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-pvc
