apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      # This points to the Vault Service inside the cluster
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"  # This matches the KV engine created in the UI
      version: "v2"   # Mandatory for the modern Vault deployed
      auth:
        tokenSecretRef:
          name: vault-token      # It looks for a secret with this name...
          key: token             # ...and looks for this specific key inside it
          namespace: external-secrets
