# 1. Server Configuration (The Backend)
server:
  dev:
    enabled: true
  
  # Minimal Resources for cluster
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

# 2. UI Configuration (The Frontend)
ui:
  enabled: true
  serviceType: "ClusterIP"
  serviceNodePort: null
  externalPort: 8200

  # 3. Ingress Configuration - DISABLED
  # Set this to 'false' because of providing 
  # a manual 'manual-ingress.yaml' file instead.
  ingress:
    enabled: false
