# Lightweight Dev Mode (Runs in RAM, Auto-Unseals)
server:
  dev:
    enabled: true
  
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

  # To enable the UI so secrets can be seen
  ui:
    enabled: true
    serviceType: ClusterIP 
    serviceNodePort: null  # Disable NodePort since using Ingress
    externalPort: 8200

# Enabled Ingress so it can be accessed via the UI
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: vault.sikiru.co.uk
          paths: []  # The chart handles the default path automatically
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cloudflare
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        # Increases buffer size for large Vault tokens/responses
        nginx.ingress.kubernetes.io/proxy-body-size: "10m"
      tls:
        - secretName: vault-tls
          hosts:
            - vault.sikiru.co.uk
